artifact_location: file:///C:/Users/maxmo/Documents/Max/train_scanner/runs/mlflow/524327714492083972
creation_time: 1774027557163
experiment_id: '524327714492083972'
last_update_time: 1774027557163
lifecycle_stage: active
name: Train_scanner
workspace: default
