artifact_location: file:///C:/Users/maxmo/Documents/Max/train_scanner/runs/mlflow/537542503713150183
creation_time: 1774021302851
experiment_id: '537542503713150183'
last_update_time: 1774021302851
lifecycle_stage: active
name: runs/train
workspace: default
