artifact_location: file:///C:/Users/maxmo/Documents/Max/train_scanner/runs/mlflow/0
creation_time: 1774021302824
experiment_id: '0'
last_update_time: 1774021302824
lifecycle_stage: active
name: Default
workspace: default
